import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Activity, ArrowDownRight, ArrowUpRight, BadgeCheck, Bell, ChevronDown, CircleHelp, Copy, CreditCard, Download, KeyRound, LayoutDashboard, LifeBuoy, LogOut, Menu, MoreHorizontal, Plus, Search, Settings2, Shield, Smartphone, Users, X } from "lucide-react";
import { useState } from "react";

const summary = [
  { label: "MRR estimado", value: "R$ 18.420", change: "+12,4%", tone: "coral", icon: CreditCard },
  { label: "Licenças ativas", value: "1.284", change: "+8,2%", tone: "lime", icon: KeyRound },
  { label: "Em teste", value: "186", change: "+21,6%", tone: "amber", icon: Activity },
  { label: "Churn mensal", value: "2,8%", change: "−0,6%", tone: "blue", icon: ArrowDownRight },
];
const activity = [
  { name: "Marina Costa", initials: "MC", email: "marina@atelier.co", plan: "Pro mensal", status: "Ativa", key: "SNYX-7K4-M9Q.API", time: "há 8 min", color: "#f36c4d" },
  { name: "Rafael Nunes", initials: "RN", email: "rafael@orbita.dev", plan: "Studio anual", status: "Ativa", key: "SNYX-4B2-PQ8.API", time: "há 31 min", color: "#d9f5b2" },
  { name: "Ana Beatriz", initials: "AB", email: "ana@northlab.io", plan: "Free trial", status: "Em teste", key: "SNYX-9H1-K2M.API", time: "há 1 h", color: "#d9b8ff" },
  { name: "João Victor", initials: "JV", email: "joao@fluxo.app", plan: "Pro mensal", status: "Pausada", key: "SNYX-3N7-T6R.API", time: "há 2 h", color: "#f4d06f" },
];

function Logo() { return <div className="flex items-center gap-2.5 text-[#f9f4ed]"><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-[#f36c4d] text-sm font-black text-[#171717]">s.</span><span className="text-[17px] font-semibold tracking-[-.04em]">snyx.store.api</span></div>; }
function StatusPill({ status }: { status: string }) { const styles: Record<string, string> = { Ativa: "bg-[#d9f5b2] text-[#263b15]", "Em teste": "bg-[#f4d06f] text-[#5b4500]", Pausada: "bg-[#d7e7fa] text-[#284a69]" }; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold ${styles[status] || "bg-white/10 text-white"}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>; }

export default function AdminDashboard() {
  const [navOpen, setNavOpen] = useState(false);
  const [active, setActive] = useState("Visão geral");
  const [search, setSearch] = useState("");
  const { user, loading, logout } = useAuth();
  const filtered = activity.filter((item) => `${item.name} ${item.email} ${item.key}`.toLowerCase().includes(search.toLowerCase()));
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#171717] text-[#f9f4ed]"><div className="h-8 w-8 animate-spin rounded-full border-2 border-[#f36c4d] border-t-transparent" /></div>;
  if (!user) return <div className="grid min-h-screen place-items-center bg-[#171717] px-5 text-[#f9f4ed]"><div className="max-w-md text-center"><div className="mx-auto mb-7 grid h-16 w-16 place-items-center rounded-3xl bg-[#f36c4d] text-2xl font-black text-[#171717] shadow-[5px_5px_0_#d9f5b2]">s.</div><h1 className="text-4xl font-semibold tracking-[-.07em]">Seu console começa aqui.</h1><p className="mt-4 text-sm leading-6 text-[#f9f4ed]/50">Entre para gerenciar clientes, planos, licenças e dispositivos do snyx.store.api.</p><Button onClick={() => startLogin()} className="mt-8 h-12 rounded-full bg-[#f36c4d] px-7 font-semibold text-[#171717] hover:bg-[#ff805f]">Entrar no painel <ArrowUpRight className="ml-2 h-4 w-4" /></Button></div></div>;

  return <div className="min-h-screen bg-[#f6f1e9] text-[#171717] lg:flex"><aside className={`${navOpen ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 z-50 w-[270px] bg-[#171717] p-5 text-[#f9f4ed] transition-transform lg:relative lg:translate-x-0`}><div className="flex items-center justify-between"><Logo /><button onClick={() => setNavOpen(false)} className="lg:hidden"><X className="h-5 w-5" /></button></div><div className="mt-14 text-[10px] font-bold uppercase tracking-[.2em] text-[#f9f4ed]/30">WORKSPACE</div><nav className="mt-4 space-y-1">{[[LayoutDashboard,"Visão geral"],[KeyRound,"Licenças"],[Users,"Clientes"],[CreditCard,"Assinaturas"],[Activity,"Atividade"]].map(([Icon, label]) => <button key={label as string} onClick={() => { setActive(label as string); setNavOpen(false); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${active === label ? "bg-[#f36c4d] font-semibold text-[#171717]" : "text-[#f9f4ed]/55 hover:bg-white/5 hover:text-[#f9f4ed]"}`}><Icon className="h-4 w-4" />{label as string}{label === "Licenças" && <span className="ml-auto rounded-full bg-white/10 px-2 py-0.5 text-[10px]">1.2k</span>}</button>)}</nav><div className="mt-12 text-[10px] font-bold uppercase tracking-[.2em] text-[#f9f4ed]/30">CONFIGURAÇÕES</div><nav className="mt-4 space-y-1">{[[Settings2,"Preferências"],[LifeBuoy,"Suporte"]].map(([Icon, label]) => <button key={label as string} onClick={() => toast.info(`${label} estará disponível em breve.`)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm text-[#f9f4ed]/55 transition hover:bg-white/5 hover:text-[#f9f4ed]"><Icon className="h-4 w-4" />{label as string}</button>)}</nav><div className="absolute inset-x-5 bottom-5 border-t border-white/10 pt-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#d9f5b2] text-xs font-bold text-[#171717]">{(user.name || "S").slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{user.name || "Admin"}</p><p className="truncate text-[10px] text-white/40">{user.email || "owner@snyx.store.api"}</p></div><button onClick={() => logout()} className="text-white/35 hover:text-white" title="Sair"><LogOut className="h-4 w-4" /></button></div></div></aside>{navOpen && <div className="fixed inset-0 z-40 bg-black/40 lg:hidden" onClick={() => setNavOpen(false)} />}
    <main className="min-w-0 flex-1"><header className="flex h-[76px] items-center justify-between border-b border-[#171717]/10 bg-[#f6f1e9] px-5 lg:px-10"><div className="flex items-center gap-4"><button onClick={() => setNavOpen(true)} className="lg:hidden"><Menu className="h-5 w-5" /></button><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#f36c4d]">CONSOLE / {active.toUpperCase()}</p><h1 className="mt-1 text-xl font-semibold tracking-[-.04em]">Bom dia, {user.name?.split(" ")[0] || "admin"}.</h1></div></div><div className="flex items-center gap-3"><button className="relative grid h-10 w-10 place-items-center rounded-full border border-[#171717]/10 hover:bg-white"><Bell className="h-4 w-4" /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[#f36c4d]" /></button><div className="hidden h-8 w-px bg-[#171717]/10 sm:block" /><div className="hidden items-center gap-2 text-xs font-medium sm:flex"><div className="h-7 w-7 rounded-full bg-[#f36c4d]" />{user.name || "Admin"}<ChevronDown className="h-3.5 w-3.5 opacity-50" /></div></div></header>
      <div className="p-5 lg:p-10"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm text-[#171717]/45">Visão dos últimos 30 dias</p><div className="mt-2 flex items-center gap-3"><span className="rounded-full bg-[#d9f5b2] px-2.5 py-1 text-[10px] font-bold text-[#263b15]">● SISTEMA SAUDÁVEL</span><span className="text-xs text-[#171717]/35">Atualizado agora</span></div></div><div className="flex gap-2"><Button variant="outline" onClick={() => toast.success("Relatório preparado para download.")} className="h-10 rounded-full border-[#171717]/15 bg-transparent text-xs"><Download className="mr-2 h-3.5 w-3.5" /> Exportar</Button><Button onClick={() => toast.success("Nova licença pronta para configurar.")} className="h-10 rounded-full bg-[#171717] text-xs text-[#f9f4ed] hover:bg-[#333]"><Plus className="mr-2 h-3.5 w-3.5" /> Nova licença</Button></div></div>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{summary.map((item) => <div key={item.label} className={`rounded-[20px] p-5 ${item.tone === "coral" ? "bg-[#f36c4d]" : item.tone === "lime" ? "bg-[#d9f5b2]" : item.tone === "amber" ? "bg-[#f4d06f]" : "bg-[#d7e7fa]"}`}><div className="flex items-start justify-between"><span className="text-xs font-semibold opacity-60">{item.label}</span><item.icon className="h-4 w-4 opacity-55" /></div><div className="mt-7 flex items-end justify-between"><strong className="text-3xl font-semibold tracking-[-.07em]">{item.value}</strong><span className="text-[10px] font-bold opacity-60">{item.change}</span></div></div>)}</div>
        <div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_.6fr]"><section className="rounded-[22px] bg-[#171717] p-6 text-[#f9f4ed]"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#f36c4d]">RECEITA RECORRENTE</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.06em]">Crescimento constante.</h2></div><button onClick={() => toast.info("Filtros de período em breve.")} className="rounded-full border border-white/15 px-3 py-1.5 text-[10px] text-white/55">Últimos 30 dias <ChevronDown className="ml-1 inline h-3 w-3" /></button></div><div className="mt-10 flex h-[190px] items-end gap-2 border-b border-white/10 px-1">{[42,48,45,58,64,61,72,69,78,74,88,94].map((height, i) => <div key={i} className="group relative h-full flex-1"><div className="absolute -top-6 left-1/2 -translate-x-1/2 text-[9px] text-[#f36c4d] opacity-0 transition group-hover:opacity-100">{height}</div><div className={`w-full rounded-t-md transition hover:bg-[#ff805f] ${i === 11 ? "bg-[#f36c4d]" : "bg-[#f9f4ed]/20"}`} style={{ height: `${height}%`, marginTop: `${100 - height}%` }} /></div>)}</div><div className="mt-4 flex justify-between text-[9px] uppercase tracking-[.12em] text-white/30"><span>Jun 01</span><span>Jun 08</span><span>Jun 15</span><span>Jun 22</span><span>Jun 30</span></div></section><section className="rounded-[22px] bg-[#d9f5b2] p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#171717]/45">DISTRIBUIÇÃO</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.06em]">Planos ativos</h2></div><MoreHorizontal className="h-4 w-4 opacity-45" /></div><div className="mt-10 flex items-center justify-center"><div className="relative grid h-40 w-40 place-items-center rounded-full" style={{ background: "conic-gradient(#171717 0 61%, #f36c4d 61% 87%, #f4d06f 87% 100%)" }}><div className="grid h-28 w-28 place-items-center rounded-full bg-[#d9f5b2]"><div className="text-center"><strong className="block text-3xl tracking-[-.08em]">1.4k</strong><span className="text-[10px] opacity-50">clientes</span></div></div></div></div><div className="mt-7 grid grid-cols-3 gap-2 text-[10px] font-semibold"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#171717]" />Pro 61%</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#f36c4d]" />Studio 26%</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#f4d06f]" />Trial 13%</span></div></section></div>
        <section className="mt-4 rounded-[22px] border border-[#171717]/10 bg-[#fffdf8] p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#f36c4d]">ATIVIDADE RECENTE</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.06em]">Últimas licenças.</h2></div><div className="flex items-center gap-2 rounded-full border border-[#171717]/10 px-3 py-2"><Search className="h-3.5 w-3.5 opacity-40" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar cliente ou chave" className="w-full bg-transparent text-xs outline-none placeholder:text-[#171717]/35 md:w-48" /></div></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-[#171717]/10 text-[10px] uppercase tracking-[.14em] text-[#171717]/40"><th className="pb-3 font-semibold">Cliente</th><th className="pb-3 font-semibold">Plano</th><th className="pb-3 font-semibold">Licença</th><th className="pb-3 font-semibold">Status</th><th className="pb-3 text-right font-semibold">Atividade</th><th /></tr></thead><tbody>{filtered.map((item) => <tr key={item.email} className="border-b border-[#171717]/7 last:border-0"><td className="py-4"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-full text-[10px] font-bold" style={{ background: item.color }}>{item.initials}</div><div><div className="text-xs font-semibold">{item.name}</div><div className="mt-0.5 text-[10px] text-[#171717]/40">{item.email}</div></div></div></td><td className="py-4 text-xs text-[#171717]/65">{item.plan}</td><td className="py-4"><button onClick={() => { navigator.clipboard?.writeText(item.key); toast.success("Chave copiada."); }} className="flex items-center gap-2 font-mono text-[10px] text-[#171717]/60 hover:text-[#171717]">{item.key}<Copy className="h-3 w-3" /></button></td><td className="py-4"><StatusPill status={item.status} /></td><td className="py-4 text-right text-[10px] text-[#171717]/40">{item.time}</td><td className="py-4 text-right"><button onClick={() => toast.info(`Detalhes de ${item.name}`)}><MoreHorizontal className="h-4 w-4 opacity-45" /></button></td></tr>)}</tbody></table></div></section>
        <div className="mt-4 grid gap-4 md:grid-cols-3"><div className="rounded-[20px] bg-[#f36c4d] p-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#171717] text-[#f36c4d]"><Smartphone className="h-4 w-4" /></div><span className="text-xs font-semibold">Dispositivos conectados</span></div><div className="mt-6 flex items-end justify-between"><span className="text-3xl font-semibold tracking-[-.07em]">2.186</span><span className="text-[10px] font-bold opacity-60">+14 esta semana</span></div></div><div className="rounded-[20px] border border-[#171717]/10 bg-white/45 p-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#d9f5b2]"><BadgeCheck className="h-4 w-4" /></div><span className="text-xs font-semibold">Taxa de ativação</span></div><div className="mt-6 flex items-end justify-between"><span className="text-3xl font-semibold tracking-[-.07em]">82.4%</span><span className="text-[10px] font-bold text-[#4e8a26]">+4,1%</span></div></div><div className="rounded-[20px] border border-[#171717]/10 bg-white/45 p-5"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#d7e7fa]"><CircleHelp className="h-4 w-4" /></div><span className="text-xs font-semibold">Tickets abertos</span></div><div className="mt-6 flex items-end justify-between"><span className="text-3xl font-semibold tracking-[-.07em]">18</span><span className="text-[10px] font-bold text-[#4a79a4]">−12,5%</span></div></div></div>
      </div></main></div>;
}
