import { count, desc, eq } from "drizzle-orm";
import { extensionEvents, globalControls, licenseDevices, licenses, securityAlerts, supportTickets, userPreferences, users } from "../drizzle/schema";
import { getDb } from "./db";

export async function listAdminLicenses() { const db = await getDb(); if (!db) return []; return db.select({ id: licenses.id, key: licenses.key, plan: licenses.plan, status: licenses.status, maxDevices: licenses.maxDevices, expiresAt: licenses.expiresAt, createdAt: licenses.createdAt, userId: users.id, name: users.name, email: users.email }).from(licenses).leftJoin(users, eq(licenses.userId, users.id)).orderBy(desc(licenses.createdAt)).limit(100); }
export async function listAdminCustomers() { const db = await getDb(); if (!db) return []; return db.select({ id: users.id, name: users.name, email: users.email, role: users.role, createdAt: users.createdAt, lastSignedIn: users.lastSignedIn, licenseKey: licenses.key, licenseStatus: licenses.status, plan: licenses.plan }).from(users).leftJoin(licenses, eq(licenses.userId, users.id)).orderBy(desc(users.lastSignedIn)).limit(100); }
export async function listAdminSubscriptions() { const db = await getDb(); if (!db) return []; return db.select({ id: licenses.id, key: licenses.key, plan: licenses.plan, status: licenses.status, subscriptionId: licenses.stripeSubscriptionId, customer: users.name, email: users.email, createdAt: licenses.createdAt, expiresAt: licenses.expiresAt }).from(licenses).leftJoin(users, eq(licenses.userId, users.id)).orderBy(desc(licenses.createdAt)).limit(100); }
export async function listAdminEvents() { const db = await getDb(); if (!db) return []; return db.select({ id: extensionEvents.id, eventType: extensionEvents.eventType, payload: extensionEvents.payload, deviceId: extensionEvents.deviceId, createdAt: extensionEvents.createdAt, licenseKey: licenses.key, customer: users.name, email: users.email }).from(extensionEvents).leftJoin(licenses, eq(extensionEvents.licenseId, licenses.id)).leftJoin(users, eq(extensionEvents.userId, users.id)).orderBy(desc(extensionEvents.createdAt)).limit(100); }
export async function listSupportTickets() { const db = await getDb(); if (!db) return []; return db.select({ id: supportTickets.id, subject: supportTickets.subject, message: supportTickets.message, status: supportTickets.status, createdAt: supportTickets.createdAt, updatedAt: supportTickets.updatedAt, customer: users.name, email: users.email }).from(supportTickets).leftJoin(users, eq(supportTickets.userId, users.id)).orderBy(desc(supportTickets.updatedAt)).limit(100); }
export async function getAdminPreferences(userId: number) { const db = await getDb(); if (!db) return { extensionEnabled: true, emailAlerts: true }; const rows = await db.select({ extensionEnabled: userPreferences.extensionEnabled, emailAlerts: userPreferences.emailAlerts }).from(userPreferences).where(eq(userPreferences.userId, userId)).limit(1); return { extensionEnabled: Boolean(rows[0]?.extensionEnabled ?? 1), emailAlerts: Boolean(rows[0]?.emailAlerts ?? 1) }; }
export async function updateAdminPreferences(userId: number, values: { extensionEnabled?: boolean; emailAlerts?: boolean }) { const db = await getDb(); if (!db) return getAdminPreferences(userId); await db.insert(userPreferences).values({ userId, extensionEnabled: values.extensionEnabled === false ? 0 : 1, emailAlerts: values.emailAlerts === false ? 0 : 1 }).onDuplicateKeyUpdate({ set: { ...(values.extensionEnabled === undefined ? {} : { extensionEnabled: values.extensionEnabled ? 1 : 0 }), ...(values.emailAlerts === undefined ? {} : { emailAlerts: values.emailAlerts ? 1 : 0 }) } }); return getAdminPreferences(userId); }
export async function countAdminEvents() { const db = await getDb(); if (!db) return 0; const rows = await db.select({ total: count() }).from(extensionEvents); return Number(rows[0]?.total ?? 0); }
export async function getGlobalControl() { const db = await getDb(); if (!db) return { maintenanceEnabled: false, maintenanceMessage: "Extensão temporariamente em manutenção." }; const rows = await db.select({ maintenanceEnabled: globalControls.maintenanceEnabled, maintenanceMessage: globalControls.maintenanceMessage }).from(globalControls).where(eq(globalControls.id, 1)).limit(1); return { maintenanceEnabled: Boolean(rows[0]?.maintenanceEnabled ?? 0), maintenanceMessage: rows[0]?.maintenanceMessage || "Extensão temporariamente em manutenção." }; }
export async function setGlobalControl(userId: number, enabled: boolean, message?: string) { const db = await getDb(); if (!db) return getGlobalControl(); await db.insert(globalControls).values({ id: 1, maintenanceEnabled: enabled ? 1 : 0, maintenanceMessage: message || "Extensão temporariamente em manutenção.", updatedBy: userId }).onDuplicateKeyUpdate({ set: { maintenanceEnabled: enabled ? 1 : 0, ...(message === undefined ? {} : { maintenanceMessage: message }), updatedBy: userId } }); return getGlobalControl(); }
export async function createSecurityAlert(input: { userId?: number | null; licenseId?: number | null; deviceId?: string | null; alertType: string; message: string; payload?: unknown }) { const db = await getDb(); if (!db) return; await db.insert(securityAlerts).values({ userId: input.userId ?? null, licenseId: input.licenseId ?? null, deviceId: input.deviceId || null, alertType: input.alertType.slice(0, 96), message: input.message.slice(0, 255), payload: JSON.stringify(input.payload || {}) }); }
export async function listSecurityAlerts() { const db = await getDb(); if (!db) return []; return db.select({ id: securityAlerts.id, alertType: securityAlerts.alertType, message: securityAlerts.message, deviceId: securityAlerts.deviceId, resolved: securityAlerts.resolved, payload: securityAlerts.payload, createdAt: securityAlerts.createdAt, licenseKey: licenses.key, customer: users.name }).from(securityAlerts).leftJoin(licenses, eq(securityAlerts.licenseId, licenses.id)).leftJoin(users, eq(securityAlerts.userId, users.id)).orderBy(desc(securityAlerts.createdAt)).limit(100); }
export async function resolveSecurityAlert(id: number) { const db = await getDb(); if (!db) return; await db.update(securityAlerts).set({ resolved: 1 }).where(eq(securityAlerts.id, id)); }
